<a href="https://colab.research.google.com/github/ChavanSnehal322/Learning-TensorFlow/blob/main/1_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Intro to Tensorflow

In [2]:
import tensorflow as tf

print(tf.__version__)  # version =  2.19.0

2.19.0


In [3]:
# creating a constant tensor for a tensor like object with tf.constant()
#  scalar = a single number

scalar = tf.constant(6)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [4]:

#  checking the number of dimensions of a tensor ( ndim = no. of dimensions)

scalar.ndim

0

In [5]:
#  creating a vector
#  vector = a number with direction( eg. : direction and wind speed)


vector = tf.constant([10, 20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [6]:
#  dimemsion of vector = 1

vector.ndim

1

In [7]:
#  creating matrix
#  Matrix = 2-D array of numbers

matrix = tf.constant( [[1, 5],
                      [9, 3] ])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [9, 3]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:

#  creating matrix with float data type

matrix_new = tf.constant( [ [ 9., 2.], [5., 3.], [6., 8.]], dtype = tf.float16)

matrix_new

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[9., 2.],
       [5., 3.],
       [6., 8.]], dtype=float16)>

In [10]:
matrix_new.ndim

2

In [11]:
#  creating a tensor
#  Tensor = n dimensional array of numbers ( n can be any numbers )
#  0-D tensor = scalar
#  1-D tensor = vector

tensor = tf.constant( [ [ [3, 6, 1], [2, 9, 2]], [[5, 2, 8], [ 2, 6, 3]], [[9, 1, 4], [1, 2, 1]] ])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[3, 6, 1],
        [2, 9, 2]],

       [[5, 2, 8],
        [2, 6, 3]],

       [[9, 1, 4],
        [1, 2, 1]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
#  creating tensor using tf.variable

changable_tensor = tf.Variable( [10, 6])

unchangeable_tensor = tf.constant( [4, 1])

changable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 1], dtype=int32)>)

In [14]:
#  changing the tensor value using .assign

changable_tensor[0].assign(5)

changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>

# Creating random tensors

 Random tensors = tensors with arbitary size which consists any random numbers

Overview of neural network learning ==> initialize random weights, give examples, update representation outputs and repeat with more examples


In [15]:
# creating random tensors of same size
#  seed for reproductivi
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal( shape=( 3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape =(3,2))

#  checking if both are equal
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffling tensor data

In [16]:
tens = tf.constant([[5, 2], [9, 4], [3, 1] ])

#  suffing the tens tensor based on first dimension ( the pairs remain same only order of pairs channges)
tf.random.shuffle(tens)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 1],
       [5, 2],
       [9, 4]], dtype=int32)>

In [17]:
#  suffles the data every time the cmd is run
tf.random.shuffle(tens)

#  use set_seed to get the same result everytime the command is run
tf.random.set_seed(42)              # global level random seed
tf.random.shuffle(tens, seed=42)    # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 2],
       [9, 4],
       [3, 1]], dtype=int32)>

In [18]:
tf.random.set_seed(25)
tf.random.shuffle(tens, seed=25)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 4],
       [3, 1],
       [5, 2]], dtype=int32)>

Other ways to create a tensor

In [19]:
#  creating a tensor of all one values

tf.ones([6, 3])

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [20]:
#  creating a tensor of all zero values

tf.zeros(shape=(4, 3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
#  converting numpy arrays in to a tensors

#  difference between NUmpy arrys and tensor are that tensors run on GPU for faster computing

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant( some_matrix)         # capital X for matrix or tensor
# y = tf.constant( vector)              # small case for vector - one dimensional

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A)
#  vector is created, shape will be same as numpy array


# creating a three dimension tensor
B = tf.constant(numpy_A, shape=( 2, 3, 4))

C = tf.constant(numpy_A, shape=( 8, 3))

# C = tf.constant(numpy_A, shape=( 3, 2, 2))        # # unsupported shape error as number of elements 24 > shape passed ( 3 * 2 * 2 = 12)

#  c  = tf.constant(numpy_A, shape=( 2, 3, 5))      # unsupported shape error as number of elements 24 are less compared to ( 2 * 3 * 5 = 30)

A, B, C

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>)

In [23]:
A.ndim, B.ndim, C.ndim

(1, 3, 2)

# Tensor **attributes** to fetch information from tensors

Shape = Length/ number of elements of each dimensions of a tensor ( tensor.shape)

Rank = Number of tensor dimensions( scalar = 0, vector = 1, matrix = 2, tensor = n ) ( tensor.ndim)

Axis / dimension = Sprcific dimension of a tensor ( tensor[0], tensor[:, 1], ...

size = Total number of items in tensor ( tf.size( tensor) )

In [24]:
#  creating tensor of rank 4 ( 4 D tensor )

rank_4_tens = tf.ones( shape =( 2, 4, 2, 5))

rank_4_tens

<tf.Tensor: shape=(2, 4, 2, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [25]:
rank_4_tens[0]

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [26]:
rank_4_tens.shape, rank_4_tens.ndim, tf.size( rank_4_tens)

(TensorShape([2, 4, 2, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=80>)

In [27]:

#  different attributes of tensor

print( " Datatype of every elements : ", rank_4_tens.dtype)

print( " Number of dimensions(rank) : ", rank_4_tens.ndim)

print( " Shape of tensor : " , rank_4_tens.shape)
print( " Elements along 0 axis : ", rank_4_tens.shape[0])
print(" Elements along last axis : ", rank_4_tens.shape[-1])
print( " Total number of elements in tensor : ", tf.size( rank_4_tens))

print( " Total number of elements in tensor : ", tf.size( rank_4_tens).numpy())  # single count of elements

 Datatype of every elements :  <dtype: 'float32'>
 Number of dimensions(rank) :  4
 Shape of tensor :  (2, 4, 2, 5)
 Elements along 0 axis :  2
 Elements along last axis :  5
 Total number of elements in tensor :  tf.Tensor(80, shape=(), dtype=int32)
 Total number of elements in tensor :  80


Index and expand on tensors

In [28]:
Examp_list = [1, 2, 4, 5]

Examp_list[:2]

[1, 2]

In [29]:
#  indexing tensors like python lists

#  fetching first 2 elements of each dimension

rank_4_tens[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [30]:
Examp_list[:1]


[1]

In [31]:
#  getting first element from each dimension from each index except the last one
rank_4_tens[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [32]:
#  creating a rank 2 tensor ( matrix)

rank2_tens = tf.constant([[5, 2], [9, 4]])

rank2_tens.shape, rank2_tens.ndim

(TensorShape([2, 2]), 2)

In [33]:
#  Extracting last item from each row

rank2_tens[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 2]], dtype=int32)>

In [34]:
#  Adding extra dimension to rank2 tensor, keeping old data same
#  newaxis adds a new dimension to the existing tensor at last axis

rank3_tens = rank2_tens[..., tf.newaxis]
rank3_tens


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [2]],

       [[9],
        [4]]], dtype=int32)>

In [35]:
#  tf.expand_dim() , alternate to tf.newaxis() to expand final axis(-1) in existing tensor

tf.expand_dims(rank2_tens, axis = -1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [2]],

       [[9],
        [4]]], dtype=int32)>

In [36]:
#  expanding the 0th axis

tf.expand_dims(rank2_tens, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 2],
        [9, 4]]], dtype=int32)>

In [37]:
#  expanding the 1st axis

tf.expand_dims(rank2_tens, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[5, 2]],

       [[9, 4]]], dtype=int32)>

Tensor operations

In [38]:
#  Basic operations : ( +, -, *, /)

#  Adding values to a tensor using Addition operation (+)

tensor = tf.constant([[ 10, 7], [3, 4 ] ] )

tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
#  Original tensor is unchanged unless assigned to a veriable

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [40]:
#  Multiply

tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

In [41]:
#  Substract

tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [42]:
#  Tensorflow built in functions  ( to speed up the operations, use tf inbuilt function)

#  Multiply
tf.multiply(tensor , 5), tf.math.add(tensor, 5) , tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[50, 35],
        [15, 20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 12],
        [ 8,  9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [43]:
#  Matrix multiplication ( common operations ) with tensors
#  mathmul = matrix multiplicatn, linalg = linear algebra
#  the inner dimensions of matrix to be multiplied should be same
#  resultant matric has shape of outer dimensions of matrix

tf.linalg.matmul( tensor, tensor), tf.matmul(tensor, tensor)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [44]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [45]:
#  @ in python is used for matrix multiplication

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [46]:
tensor.shape

TensorShape([2, 2])

In [55]:
#  multiplication on matrix of different shapes

x = tf.constant([[1, 2, 5], [3, 4, 6]])
y = tf.constant([[8, 9, 12] , [10, 11, 13], [14, 15, 16]])

x.shape , y.shape, tf.matmul(x, y)

(TensorShape([2, 3]),
 TensorShape([3, 3]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 98, 106, 118],
        [148, 161, 184]], dtype=int32)>)

In [56]:
tf.transpose(x), tf.reshape(x, shape = (2, 3) )

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [3, 4, 6]], dtype=int32)>)

In [57]:
#  multiplication using transpose

tf.matmul( tf.transpose(y), y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[360, 392, 450],
       [392, 427, 491],
       [450, 491, 569]], dtype=int32)>

In [58]:
tf.matmul( x, y), x, y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 98, 106, 118],
        [148, 161, 184]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [3, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 8,  9, 12],
        [10, 11, 13],
        [14, 15, 16]], dtype=int32)>)

In [61]:
#  matrix mul between x and y transposed

tf.matmul( x, tf.transpose(y))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 86,  97, 124],
       [132, 152, 198]], dtype=int32)>

In [63]:
#  matrix mul between x and y reshape

tf.matmul( x, tf.reshape( y, shape =(3,3) ) )

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 98, 106, 118],
       [148, 161, 184]], dtype=int32)>

In [73]:
#
print( " Original y: ")
print( y, "\n")

print( " Y reshaped to ( 1, 9 ):")
print( tf.reshape( y, ( 1, 9) ), "\n" )

print( " Y transpose: ")
print( tf.transpose( y))

 Original y: 
tf.Tensor(
[[ 8  9 12]
 [10 11 13]
 [14 15 16]], shape=(3, 3), dtype=int32) 

 Y reshaped to ( 1, 9 ):
tf.Tensor([[ 8  9 12 10 11 13 14 15 16]], shape=(1, 9), dtype=int32) 

 Y transpose: 
tf.Tensor(
[[ 8 10 14]
 [ 9 11 15]
 [12 13 16]], shape=(3, 3), dtype=int32)


Changing a data type of Tensor ( from int 32)

In [74]:
#  creating tensor of default data type as float32
#  Default data type is decided according to the data in the tensor

A = tf.constant( [2.9, 5.8])

A.dtype

tf.float32

In [75]:
#  Reduced precision ( converting float32 to float16 that store data in 16 bits of memory)

C = tf.cast( A, dtype=tf.float16)

C, C.dtype


(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.9, 5.8], dtype=float16)>,
 tf.float16)

In [83]:
#  changing from int32 to int16

B = tf.constant([ [5, 1], [7, 2] ])

B, B.dtype


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 1],
        [7, 2]], dtype=int32)>,
 tf.int32)

In [84]:
D = tf.cast(B, dtype = tf.int16)

D, D.dtype

(<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
 array([[5, 1],
        [7, 2]], dtype=int16)>,
 tf.int16)

In [86]:
#  changing from float 32 to int32

E = tf.cast( A, dtype = tf.int32)

E, E.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>,
 tf.int32)

Aggregating operations on Tensor:

Maximum
Minimum
Mean of tensor
Sum of tensor

In [88]:
#  Getting absolute values of tensors

F = tf.constant([-7, -4])

F, tf.abs(F)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-7, -4], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [89]:
#  Tensor of shape 50 with elem between 0 and 100

G = tf.constant( np.random.randint(0, 100, size = 50 ) )

G

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74, 39,  4, 75, 49, 32, 57,  8, 99, 50, 65, 28, 90, 53, 60, 65, 87,
       81, 20, 96, 79, 24, 24, 89, 17,  1,  4, 85, 13, 46, 54,  6, 98, 54,
       72, 66, 44, 29, 66, 57, 96, 60,  0, 84, 21, 71,  2, 51, 12, 60])>

In [90]:
tf.size(G), G.shape, G.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [91]:
#  Minimum of tensor
#  returns minium value in tensor
tf.reduce_min(G)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [92]:
# Maximum of tensor

tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [93]:
#  Mean of tensor

tf.reduce_mean(G)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [97]:
#  Sum of tensor

tf.reduce_sum(G)

<tf.Tensor: shape=(), dtype=int64, numpy=2517>

In [102]:
#  Variance of tensor using tfp

#  tfp = tensorflow probability

import tensorflow_probability as tfp


tfp.stats.variance(G)

<tf.Tensor: shape=(), dtype=int64, numpy=893>

In [107]:
#  Standard deviation
#  typecast datatype to resolve type error

tf.math.reduce_std(tf.cast(G, dtype= tf.float32) )

<tf.Tensor: shape=(), dtype=float32, numpy=29.895559310913086>

In [ ]:
#  Getting the max and minimum value based on position in tensor

