<a href="https://colab.research.google.com/github/ChavanSnehal322/Learning-TensorFlow/blob/main/1_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Intro to Tensorflow

In [1]:
import tensorflow as tf

print(tf.__version__)  # version =  2.19.0

2.19.0


In [2]:
# creating a constant tensor for a tensor like object with tf.constant()
#  scalar = a single number

scalar = tf.constant(6)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [3]:

#  checking the number of dimensions of a tensor ( ndim = no. of dimensions)

scalar.ndim

0

In [4]:
#  creating a vector
#  vector = a number with direction( eg. : direction and wind speed)


vector = tf.constant([10, 20])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [5]:
#  dimemsion of vector = 1

vector.ndim

1

In [6]:
#  creating matrix
#  Matrix = 2-D array of numbers

matrix = tf.constant( [[1, 5],
                      [9, 3] ])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 5],
       [9, 3]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:

#  creating matrix with float data type

matrix_new = tf.constant( [ [ 9., 2.], [5., 3.], [6., 8.]], dtype = tf.float16)

matrix_new

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[9., 2.],
       [5., 3.],
       [6., 8.]], dtype=float16)>

In [9]:
matrix_new.ndim

2

In [10]:
#  creating a tensor
#  Tensor = n dimensional array of numbers ( n can be any numbers )
#  0-D tensor = scalar
#  1-D tensor = vector

tensor = tf.constant( [ [ [3, 6, 1], [2, 9, 2]], [[5, 2, 8], [ 2, 6, 3]], [[9, 1, 4], [1, 2, 1]] ])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[3, 6, 1],
        [2, 9, 2]],

       [[5, 2, 8],
        [2, 6, 3]],

       [[9, 1, 4],
        [1, 2, 1]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
#  creating tensor using tf.variable

changable_tensor = tf.Variable( [10, 6])

unchangeable_tensor = tf.constant( [4, 1])

changable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 1], dtype=int32)>)

In [13]:
#  changing the tensor value using .assign

changable_tensor[0].assign(5)

changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>

# Creating random tensors

 Random tensors = tensors with arbitary size which consists any random numbers

Overview of neural network learning ==> initialize random weights, give examples, update representation outputs and repeat with more examples


In [14]:
# creating random tensors of same size
#  seed for reproductivi
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal( shape=( 3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape =(3,2))

#  checking if both are equal
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffling tensor data

In [15]:
tens = tf.constant([[5, 2], [9, 4], [3, 1] ])

#  suffing the tens tensor based on first dimension ( the pairs remain same only order of pairs channges)
tf.random.shuffle(tens)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 2],
       [9, 4],
       [3, 1]], dtype=int32)>

In [16]:
#  suffles the data every time the cmd is run
tf.random.shuffle(tens)

#  use set_seed to get the same result everytime the command is run
tf.random.set_seed(42)              # global level random seed
tf.random.shuffle(tens, seed=42)    # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 2],
       [9, 4],
       [3, 1]], dtype=int32)>

In [17]:
tf.random.set_seed(25)
tf.random.shuffle(tens, seed=25)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[9, 4],
       [3, 1],
       [5, 2]], dtype=int32)>

Other ways to create a tensor

In [18]:
#  creating a tensor of all one values

tf.ones([6, 3])

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
#  creating a tensor of all zero values

tf.zeros(shape=(4, 3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
#  converting numpy arrays in to a tensors

#  difference between NUmpy arrys and tensor are that tensors run on GPU for faster computing

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant( some_matrix)         # capital X for matrix or tensor
# y = tf.constant( vector)              # small case for vector - one dimensional

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A)
#  vector is created, shape will be same as numpy array


# creating a three dimension tensor
B = tf.constant(numpy_A, shape=( 2, 3, 4))

C = tf.constant(numpy_A, shape=( 8, 3))

# C = tf.constant(numpy_A, shape=( 3, 2, 2))        # # unsupported shape error as number of elements 24 > shape passed ( 3 * 2 * 2 = 12)

#  c  = tf.constant(numpy_A, shape=( 2, 3, 5))      # unsupported shape error as number of elements 24 are less compared to ( 2 * 3 * 5 = 30)

A, B, C

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>)

In [22]:
A.ndim, B.ndim, C.ndim

(1, 3, 2)

# Tensor **attributes** to fetch information from tensors

Shape = Length/ number of elements of each dimensions of a tensor ( tensor.shape)

Rank = Number of tensor dimensions( scalar = 0, vector = 1, matrix = 2, tensor = n ) ( tensor.ndim)

Axis / dimension = Sprcific dimension of a tensor ( tensor[0], tensor[:, 1], ...

size = Total number of items in tensor ( tf.size( tensor) )

In [23]:
#  creating tensor of rank 4 ( 4 D tensor )

rank_4_tens = tf.ones( shape =( 2, 4, 2, 5))

rank_4_tens

<tf.Tensor: shape=(2, 4, 2, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [24]:
rank_4_tens[0]

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [25]:
rank_4_tens.shape, rank_4_tens.ndim, tf.size( rank_4_tens)

(TensorShape([2, 4, 2, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=80>)

In [26]:

#  different attributes of tensor

print( " Datatype of every elements : ", rank_4_tens.dtype)

print( " Number of dimensions(rank) : ", rank_4_tens.ndim)

print( " Shape of tensor : " , rank_4_tens.shape)
print( " Elements along 0 axis : ", rank_4_tens.shape[0])
print(" Elements along last axis : ", rank_4_tens.shape[-1])
print( " Total number of elements in tensor : ", tf.size( rank_4_tens))

print( " Total number of elements in tensor : ", tf.size( rank_4_tens).numpy())  # single count of elements

 Datatype of every elements :  <dtype: 'float32'>
 Number of dimensions(rank) :  4
 Shape of tensor :  (2, 4, 2, 5)
 Elements along 0 axis :  2
 Elements along last axis :  5
 Total number of elements in tensor :  tf.Tensor(80, shape=(), dtype=int32)
 Total number of elements in tensor :  80


Index and expand on tensors

In [27]:
Examp_list = [1, 2, 4, 5]

Examp_list[:2]

[1, 2]

In [28]:
#  indexing tensors like python lists

#  fetching first 2 elements of each dimension

rank_4_tens[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [29]:
Examp_list[:1]


[1]

In [30]:
#  getting first element from each dimension from each index except the last one
rank_4_tens[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[1., 1., 1., 1., 1.]]]], dtype=float32)>

In [31]:
#  creating a rank 2 tensor ( matrix)

rank2_tens = tf.constant([[5, 2], [9, 4]])

rank2_tens.shape, rank2_tens.ndim

(TensorShape([2, 2]), 2)

In [32]:
#  Extracting last item from each row

rank2_tens[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[5, 2]], dtype=int32)>

In [33]:
#  Adding extra dimension to rank2 tensor, keeping old data same
#  newaxis adds a new dimension to the existing tensor at last axis

rank3_tens = rank2_tens[..., tf.newaxis]
rank3_tens


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [2]],

       [[9],
        [4]]], dtype=int32)>

In [34]:
#  tf.expand_dim() , alternate to tf.newaxis() to expand final axis(-1) in existing tensor

tf.expand_dims(rank2_tens, axis = -1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [2]],

       [[9],
        [4]]], dtype=int32)>

In [35]:
#  expanding the 0th axis

tf.expand_dims(rank2_tens, axis = 0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 2],
        [9, 4]]], dtype=int32)>

In [36]:
#  expanding the 1st axis

tf.expand_dims(rank2_tens, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[5, 2]],

       [[9, 4]]], dtype=int32)>

Tensor operations

In [37]:
#  Basic operations : ( +, -, *, /)

#  Adding values to a tensor using Addition operation (+)

tensor = tf.constant([[ 10, 7], [3, 4 ] ] )

tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [38]:
#  Original tensor is unchanged unless assigned to a veriable

tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
#  Multiply

tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [15, 20]], dtype=int32)>

In [40]:
#  Substract

tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]], dtype=int32)>

In [43]:
#  Tensorflow built in functions  ( to speed up the operations, use tf inbuilt function)

#  Multiply
tf.multiply(tensor , 5), tf.math.add(tensor, 5) , tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[50, 35],
        [15, 20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 12],
        [ 8,  9]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [46]:
#  Matrix multiplication ( common operations ) with tensors
#  mathmul = matrix multiplicatn, linalg = linear algebra
#  the inner dimensions of matrix to be multiplied should be same
#  resultant matric has shape of outer dimensions of matrix

tf.linalg.matmul( tensor, tensor), tf.matmul(tensor, tensor)


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]], dtype=int32)>)

In [47]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [48]:
#  @ in python is used for matrix multiplication

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [49]:
tensor.shape

TensorShape([2, 2])

In [58]:
#  multiplication on matrix of different shapes

x = tf.constant([[1, 2], [3, 4], [5, 6]])
y = tf.constant([[8, 9, 12] , [10, 11, 13]])

x.shape , y.shape, tf.matmul(x, y)

(TensorShape([3, 2]),
 TensorShape([2, 3]),
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 28,  31,  38],
        [ 64,  71,  88],
        [100, 111, 138]], dtype=int32)>)

In [59]:
tf.transpose(x), tf.reshape(x, shape = (2, 3) )

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [65]:
#  multiplication using transpose

tf.matmul( tf.transpose(y), y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[164, 182, 226],
       [182, 202, 251],
       [226, 251, 313]], dtype=int32)>